<div class="paragraph">
<p>Throwing an exception during startup or shutdown results in an implementation-defined termination of the program. This is because there is no where to put <code>try</code>/<code>catch</code> blocks to catch exceptions thrown in the startup phase, when static objects are being constructed, or during the shutdown phase, when those static objects are being destroyed.</p>
</div>
<div class="paragraph">
<p>Therefore exceptions should not be thrown during the construction or destruction of static objects.</p>
</div>
<div class="sect1">
<h2 id="_noncompliant_code_example">Noncompliant Code Example</h2>
<div class="sectionbody">
<div class="listingblock">
<div class="content">
<pre>class C
{

  public:
    C ( )
    {
      throw ( 0 ); // Noncompliant; thrown before main starts
    }
    ~C ( )
    {
      throw ( 0 ); // Noncompliant; thrown after main exits
    }
};

C c; // An exception thrown in C's constructor or destructor will
     // cause the program to terminate, and will not be caught by
     // the handler in main

int main( ... )
{
  // ...</pre>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_see">See</h2>
<div class="sectionbody">
<div class="ulist">
<ul>
<li>
<p>MISRA C&#43;&#43;:2008, 15-3-1</p>
</li>
</ul>
</div>
<hr/>
</div>
</div>
<div class="sect1">
<h2 id="_implementation_specification">Implementation Specification</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_message">Message</h3>
<div class="paragraph">
<p>Remove this throw clause</p>
</div>
<hr/>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_comments_and_links">Comments And Links</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_relates_to_s1050">relates to: S1050</h3>

</div>
</div>
</div>