<div class="paragraph">
<p><code>Enumerable.Sum()</code> always executes addition in a <code>checked</code> context, so an <code>OverflowException</code> will be thrown if the value exceeds <code>MaxValue</code> even if an <code>unchecked</code> context was specified. Using an <code>unchecked</code> context anyway represents a misunderstanding of how <code>Sum</code> works.</p>
</div>
<div class="paragraph">
<p>This rule raises an issue when an <code>unchecked</code> context is specified for a <code>Sum</code> on integer types.</p>
</div>
<div class="sect1">
<h2 id="_noncompliant_code_example">Noncompliant Code Example</h2>
<div class="sectionbody">
<div class="listingblock">
<div class="content">
<pre>void Add(List&lt;int&gt; list)
{
  int d = unchecked(list.Sum());  // Noncompliant

  unchecked
  {
    int e = list.Sum();  // Noncompliant
  }
}</pre>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_compliant_solution">Compliant Solution</h2>
<div class="sectionbody">
<div class="listingblock">
<div class="content">
<pre>void Add(List&lt;int&gt; list)
{
  int d = list.Sum();

  try
  {
    int e = list.Sum();
  }
  catch (System.OverflowException e)
  {
    // exception handling...
  }
}</pre>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_exceptions">Exceptions</h2>
<div class="sectionbody">
<div class="paragraph">
<p>When the <code>Sum()</code> call is inside a <code>try-catch</code> block, no issues are reported.</p>
</div>
<div class="listingblock">
<div class="content">
<pre>void Add(List&lt;int&gt; list)
{
  unchecked
  {
    try
    {
      int e = list.Sum();
    }
    catch (System.OverflowException e)
    {
      // exception handling...
    }
  }
}</pre>
</div>
</div>
<hr/>
</div>
</div>
<div class="sect1">
<h2 id="_implementation_specification">Implementation Specification</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_message">Message</h3>
<div class="paragraph">
<p>Refactor this code to handle "OverflowException".</p>
</div>
<hr/>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_comments_and_links">Comments And Links</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_on_13_apr_2015_104427_freddy_mallet_wrote">on 13 Apr 2015, 10:44:27 Freddy Mallet wrote:</h3>
<div class="paragraph">
<p>@Tamas, according to you, does this rule makes sense ? Thanks</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_29_jun_2015_145819_tamas_vajk_wrote">on 29 Jun 2015, 14:58:19 Tamas Vajk wrote:</h3>
<div class="paragraph">
<p>\[~ann.campbell.2] I&#8217;ve modified the description to be more specific. Also, I&#8217;ve changed the examples to use <code>List&lt;int&gt;</code> because for <code>double</code>s it won&#8217;t throw the <code>OverflowException</code>.</p>
</div>
<div class="paragraph">
<p>\[~freddy.mallet] Yes, the rule makes sense.</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_30_jun_2015_144528_ann_campbell_wrote">on 30 Jun 2015, 14:45:28 Ann Campbell wrote:</h3>
<div class="paragraph">
<p>Double-check my edits please [~tamas.vajk]</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_6_jul_2015_093341_tamas_vajk_wrote">on 6 Jul 2015, 09:33:41 Tamas Vajk wrote:</h3>
<div class="paragraph">
<p>\[~ann.campbell.2] Looks good.</p>
</div>
</div>
</div>
</div>