<div class="paragraph">
<p>There&#8217;s no reason for a <code>Main</code> method to <code>throw</code> anything. After all, what&#8217;s going to catch it?</p>
</div>
<div class="paragraph">
<p>Instead, the method should itself gracefully handle any exceptions that may bubble up to it, attach as much contextual information as possible, and perform whatever logging or user communication is necessary, and <code>Exit</code> with a non-zero (i.e. non-success) exit code if necessary.</p>
</div>
<div class="sect1">
<h2 id="_noncompliant_code_example">Noncompliant Code Example</h2>
<div class="sectionbody">
<div class="listingblock">
<div class="content">
<pre>public static void Main(string[] args) { // Noncompliant
  if (args.Length == 0)
  {
    throw new ArgumentException();
  }
  // do stuff
}</pre>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_compliant_solution">Compliant Solution</h2>
<div class="sectionbody">
<div class="listingblock">
<div class="content">
<pre>private const int ERROR_INVALID_COMMAND_LINE = 0x667;
public static void Main(string[] args) { // Noncompliant
  if (args.Length == 0)
  {
    Console.WriteLine("Should provide at least one argument");
    Environment.ExitCode = ERROR_INVALID_COMMAND_LINE;
  }
  // do stuff
}</pre>
</div>
</div>
<hr/>
</div>
</div>
<div class="sect1">
<h2 id="_implementation_specification">Implementation Specification</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_message">Message</h3>
<div class="paragraph">
<p>Remove this throws clause.</p>
</div>
<hr/>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_comments_and_links">Comments And Links</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_on_30_sep_2019_092007_andrei_epure_wrote">on 30 Sep 2019, 09:20:07 Andrei Epure wrote:</h3>
<div class="paragraph">
<p>\[~nicolas.harraudeau] - this rule is not as useful for Java, where there&#8217;s the <code>throws</code> keyword in the method signature if there is a call to a method that throws an exception. In C#, there&#8217;s no such mechanism, so we can just look if there&#8217;s a <code>throw</code> inside the method body. Is this useful enough?</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_30_sep_2019_104516_nicolas_harraudeau_wrote">on 30 Sep 2019, 10:45:16 Nicolas Harraudeau wrote:</h3>
<div class="paragraph">
<p>\[~andrei.epure] indeed the value of this rule is lower. The only real-world use case I see is if there is a <code>throw</code> in a <code>try-catch</code> block and the exceptions caught do not match the one thrown. &#8658; Unintentional throw outside of the try-catch block. This is a corner case which will happen very rarely so there is no point in implementing the rule for C#.</p>
</div>
</div>
</div>
</div>